overwrite: false
subject: sf
privateAlias: privateKey
keyPass: keypass@123456
storePass: storepass@123456
licensePath: ${user.home}/.gosf
privateKeysStorePath: ""
issuedTime: 2024-07-08T14:54:59.504456+08:00
expiryTime: 2034-07-16T14:54:59.504456+08:00
consumerType: gosf
consumerAmount: 1
description: 产品授权许可证书
licenseCheckModel:
    ipAddress:
        - 192.168.20.79
        - 10.8.0.14
    macAddress:
        - 5c:e9:1e:7a:93:3c
    cpuSerial:
        - apple m2max
    mainBoardSerial: apple mb
extra:
    nodes: []
